config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/home'
  get 'pages/help'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/show_vertical'
  get 'pages/search'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :products do
    resources :reviews
  end
  resources :categories
  resources :verticals
  resources :orders
  resources :wishlist
  get 'pages/seller'
  get 'pages/cart'
  get 'pages/checkout_success'
  get 'pages/profile'
  get 'cart/add' => 'cart#add'
  delete 'cart/remove'=>'cart#remove'
end

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/cart.html.haml
%h1
  CART

- if @cart_products.nil?
  Your cart is empty
- else
  Items in your cart:
  %ul
    -@cart_products.each do |p|
      %li
        =link_to p.name, product_path(p)
        %br
        %ul
          %li
            =link_to "Remove item", cart_remove_path(cart: {product_id: p.id, user_id: current_user.id}), method: :delete
  %br
  %br
  %br
  = link_to "Checkout", new_order_path(order_params:{products:@cart_products})

  
  

app/views/pages/checkout_success.html.haml
%h1 Items checked-out successfully

%h2
=link_to "Home Page", "/pages/home"

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

app/views/pages/help.html.haml
%h1 Pages#help
%p Find me in app/views/pages/help.html.haml

app/views/pages/home.html.haml
%h1 Welcome to Amazekart!!!
%h2 The one-stop-shop for all your needs!!

%h4 Find products across these categories
%ul
  - @verticals.each do |v|
    %li 
      = link_to  v.name , vertical_path(v)
%br/
%h4 Top Products :
%ul
  - @top_products.each do |product|
    %li
      = product.name 
      %br/
      = product.description
      %br/

app/views/pages/profile.html.haml
%h1 Past Orders
- if @previous_orders.empty?
  %h2 No orders yet. Buy something fun!!!
-@previous_orders.pluck(:id).uniq.each do |order_id|
  %h3
    Order ID: 
    =order_id
  %br
  Date Purchased:
  =Order.find(order_id).created_at
  %h4 
  Products:
  %table
    %tr
    %th Name
    %th Price
  
    - Product.find(OrderItem.where(order_id: order_id).pluck(:product_id)).each do |product|
      
      %tr
      %td= product.name
      %td= product.price
  %br
  Total:
  =Order.find(order_id).price.to_f
    

app/views/pages/search.html.haml
%h1 
  Search Results for "
  =@query
  "
-@results.each do |product|
  =link_to product.name, product_path(product)
  %br

app/views/pages/seller.html.haml
- if current_user.seller?
  %h1 Seller Dashboard
  Total earnings:
  = @seller_details[:total_revenue]
  %br 
  %br
  %h3 Orders
  %table
    %tr
    %th Name
    %th Price
    %th Quantity
    %th Date Ordered
  
    - @seller_details[:sold_items].each do |item|
      - product = item.product    
      %tr
      %td= link_to product.name, product_path(product.id)
      %td= product.price
      %td= item.quantity
      %td= item.created_at
  %br 
  %br 
  = link_to "Add a new product", new_product_path
  %h5 Product List
  - if @seller_details[:products].any?  
    %table
      %tr
        %th Name
        %th Description
        %th Stock
        %th Price
  
      - @seller_details[:products].each do |product|
        %tr
          %td= product.name
          %td= product.description
          %td= product.stock
          %td= product.price
          %td= link_to 'Show', product_path(product)
          %td= link_to 'Edit', edit_product_path(product)
  - else 
    %p No products to show. Please add products. 
-else
  %h1 You are not a seller
  %p Login to your account and change settings if you wish to sell items!!