config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/home'
  get 'pages/help'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/show_vertical'
  get 'pages/search'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :products do
    resources :reviews
  end
  resources :categories
  resources :verticals
  resources :orders
  resources :wishlist
  get 'pages/seller'
  get 'pages/cart'
  get 'pages/checkout_success'
  get 'pages/profile'
  get 'cart/add' => 'cart#add'
  delete 'cart/remove'=>'cart#remove'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :order_item
  belongs_to :order
  has_many :wishlists
  has_many :reviews
  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {minimum: 5}
  validates :stock, presence: true, numericality: {only_integer: true, greater_than: -1}
  validates :price, presence: true, numericality: { greater_than: 0}
  validates :discount, presence: true, numericality: { greater_than_or_equal_to: 0}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  USER_ID = "user_id"

  def show
    @product = Product.find(params[:id])
    if current_user
      @added_to_wishlist = Wishlist.find_by(user_id:current_user.id, product_id:@product.id)
    end
    @in_cart = product_in_cart?
  end
  
  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)
 
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :category_id, :price, :stock, :discount).merge(user_id: current_user.id)
  end

  def show_by_seller(seller)
    
  end

  def product_in_cart?
    product_to_find = params[:id].to_s
    cart = JSON.parse(cookies[:cart])
    user_cart = cart[current_user.id.to_s]
    return if user_cart.nil?
    products = cart[current_user.id.to_s]["products"]
    products.include? product_to_find    
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
- if @product.errors.any?
  %h2
    = pluralize(@product.errors.count, "error")
    prohibited this product from being saved:
  %ul
    - @product.errors.full_messages.each do |msg|
      %li= msg
= form_with model:@product , local:true do |form|
  %p
    = form.label :title
    %br/
    = form.text_field :name
  %p
    = form.label :description
    %br/
    = form.text_area :description
  %p
    = form.label :category
    %br/
    = form.collection_select :category_id, Category.all, :id, :name
  %p
    = form.label :price
    %br/
    = form.number_field :price
  %p
    = form.label :stock
    %br/
    = form.number_field :stock
  %p
    = form.label :discount_offered
    %br/
    = form.number_field :discount
  %p
    = form.submit

app/views/products/edit.html.haml
%h2 Edit product!!

= render 'form', product: @product

app/views/products/new.html.haml
%h2 Add a new product!!
by 
= current_user.email
= render 'form', product: @product

app/views/products/show.html.haml
%h1 Product Detail
%p
  %strong Name:
  = @product.name
%p
  %strong Description:
  = @product.description
%p
  %strong Price:
  = @product.price
%p
  %strong Sale Price:
  = @product.price - @product.discount

- if current_user 
  - if current_user.id == @product.user_id
    = link_to "Edit Product", edit_product_path(@product)
  -else
    - if @in_cart
      = "Item in Cart, Checkout now!!"
    -else
      = link_to "Add to Cart", cart_add_path(cart: {product_id: @product.id, user_id: current_user.id})
    %br
    - if @added_to_wishlist.nil?
      = link_to "Add to Wishlist", wishlist_index_path(:wishlist => {:product_id => @product.id, :user_id => current_user.id}), method: :post
    -else
      = "Added to Wishlist" 
- else
  = link_to "Login to purchase this item", new_user_session_path

%h2 Reviews
-if current_user.id!=@product.user_id
  =link_to "Add a Review", new_product_review_path(@product)
%br
%br
%br

- @product.reviews.each do |review|
  Rating: 
  =review.rating
  Review:
  =review.review
  - if review.user_id==current_user.id
    = link_to 'Edit', edit_product_review_path(@product, review)
    = link_to 'Delete', product_review_path(@product, review) , method: :delete
    %br