config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/home'
  get 'pages/help'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/show_vertical'
  get 'pages/search'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :products do
    resources :reviews
  end
  resources :categories
  resources :verticals
  resources :orders
  resources :wishlist
  get 'pages/seller'
  get 'pages/cart'
  get 'pages/checkout_success'
  get 'pages/profile'
  get 'cart/add' => 'cart#add'
  delete 'cart/remove'=>'cart#remove'
end

app/views/layouts/_footer.html.haml
%footer
  AmazeKart by GS

  .nav
    %ul
      %li 
        =link_to "About", pages_about_path 
      %li 
        =link_to "Contact", pages_contact_path
       
  

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    .nav
      = link_to "AmazeKart",root_path, id:"logo"
      = form_tag(pages_search_path, :method => "get", |
        class: 'navbar-form navbar-left') do         |
        .input-group
          .search-input
            = text_field_tag("search[query]")
          .input-group-btn
            = button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil
      %ul.nav.navbar-nav.navbar-right
        %li 
          =link_to 'Home', pages_home_path 
        - if user_signed_in?
          %li
            =link_to 'Wishlist', wishlist_index_path(current_user.id), method: :get
          %li
            =link_to 'Cart', pages_cart_path(current_user.id), method: :get
          - if current_user.seller?
            %li 
              = link_to 'Seller Page', pages_seller_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Orders", pages_profile_path
              %li= link_to "Settings", edit_user_registration_path, method: :get
              %li.divider
              %li
                = link_to "Log out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Log in", user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Amazekart
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{class: "alert alert-#{message_type}"}= message
      = yield
    =render 'layouts/footer'